### PR TITLE
Release 0.3

### LINKED ISSUE #73: Resolve button conflicts
Let's assume we have input attached to two entities, one has mapped a chord [ctrl, a], and the other just [a]. If ctrl-a is pressed, the common sense response would be only to run the first action, but in this plugin both are run. 

The problem seems to be already solved in alternative crates, e.g. https://github.com/lightsoutgames/bevy_input_actionmap, would be nice to have it here too.

### PR DESCRIPTION
**Pull request by alice-i-cecile**
This release is planned to center around:

- ~~handling game stick inputs~~
- assorted usability improvements
- clash handling

## Issues

- Closes #73

## Critical questions

- [x] if we gather axis data into an `AxisPair` struct, where is it stored?
  - Store as `Res<AxisPairs<Gamepad>>`, with the ability to extend to other simulated axes
- [x] how are axis-like inputs used to set `ActionState`?
   - new `UserInput` variant based on direction partition clamping
   - set value of variant based on AxisPair direction / vec2 / rotation
- [x] if we want to store data in actionlike variants, how do we generate a variant-only Hash impl?
  - This isn't feasible: see #60. We also no longer need `Hash` 😄
- [x] do we care, at all, about non-enum Actionlike types? If yes, how do we refactor to support this?
  - Nope! See below.

### CODE REVIEW

**Comment by chrisburnor** [comment]
>  do we care, at all, about non-enum Actionlike types? If yes, how do we refactor to support this?
 
In my personal input manager, I implemented a system that used `HashMap<TypeId, KeyPress>` to allow heterogeneous types of actions. I also successfully experimented with using PolyMaps and TypeMaps to allow metadata to be attached to the actions rather than just using the TypeId. So, those approaches could work for the refactor.

However, after doing all that, I'm not convinced that non-enum actions are actually worth the overhead. Most games are going to end up with a relatively finite number of 'moves' corresponding to the finite gamepad keys and if one wants to let players remap the keys and then save that option, they're going to need to implement De/Serialize.

**Comment by alice-i-cecile** [comment]
@chrisburnor thanks for the feedback!

> However, after doing all that, I'm not convinced that non-enum actions are actually worth the overhead

Yeah, this is about my conclusion too: it seems like such a rare and unintuitive use case that it's not worth the significant complexity to write and maintain.

**Comment by chrisburnor** [comment]
> in order to store arpeggios and grace periods, we must store a history of relevant input events. Where and how should this be done?

What sort of requirements does this need? Something like a circular queue implemented as an index pointer and fix-length Vec (or slice??) would allow for very fast reading/writing with no memory allocations or resizing, but I don't know if that is actually what we need here. Does it need to be thread safe? Do we need one per 'player'/input-able object? or can one global suffice?

**Comment by alice-i-cecile** [comment]
@chrisburnor, these are fantastic questions, and I'm genuinely not sure yet. As a result, I've removed arpeggios from the release, and plan to implement them later to avoid blocking other features.

**Pull request merged**
